name: "EK Perfecto"
description: "Action for checking RPM files with Perfecto"
author: "ESSENTIALKAOS"

branding:
  icon: 'package'
  color: 'white'

inputs:
  files:
    description: "List of RPM files to check"
    required: true

  image:
    description: "Name of Perfecto docker image (micro/centos7)"
    required: false
    default: "micro"

  format:
    description: "Output format (summary|tiny|short|json|xml)"
    required: false

  absolve:
    description: "Disable some checks by their ID"
    required: false

  error-level:
    description: "Return non-zero exit code if alert level greater than given (notice|warning|error|critical)"
    required: false

runs:
  using: "composite"
  steps:
    - id: perfecto-install
      name: Download Perfecto docker image
      shell: bash
      run: |
        # [perfecto-install]

        echo -e "::group::\e[34mDownloading Perfecto docker image…\e[0m"
        docker pull "essentialkaos/perfecto:${{inputs.image}}"
        echo "::endgroup::"

        echo -e "::group::\e[34mDownloading Perfecto helper script…\e[0m"
        wget -O $GITHUB_ACTION_PATH/perfecto-docker https://kaos.sh/perfecto/perfecto-docker
        chmod +x $GITHUB_ACTION_PATH/perfecto-docker
        echo "::endgroup::"

    - id: perfecto-set-options
      name: Set Perfecto options
      shell: bash
      run : |
        # [perfecto-set-options]

        declare -a options

        if [[ -n "${{inputs.format}}" ]] ; then
          options+=("-f ${{inputs.format}}")
        fi

        if [[ -n "${{inputs.absolve}}" ]] ; then
          options+=("-A ${{inputs.absolve}}")
        fi

        if [[ -n "${{inputs.error-level}}" ]] ; then
          options+=("-e ${{inputs.error-level}}")
        fi

        echo -e "::group::\e[34mPerfecto configuration…\e[0m"
        if [[ ${#options[@]} -eq 0 ]] ; then
          echo "Options: -no-set-"
        else
          echo "Options: ${options[@]}"
        fi
        echo "::endgroup::"

        echo "::set-output name=options::${options[@]}"

    - id: perfecto-version-print
      name: Print Perfecto version info
      shell: bash
      run: |
        # [perfecto-version-print]

        echo -e "::group::\e[34mPrint Perfecto version…\e[0m"
        docker run --rm "essentialkaos/perfecto:${{inputs.image}}" --version
        echo "::endgroup::"

    - id: perfecto-check
      name: Check RPM files with Perfecto
      shell: bash
      run: |
        # [perfecto-check]

        echo -e "\e[34mRunning Perfecto…\e[0m"

        export IMAGE="essentialkaos/perfecto:${{inputs.image}}"

        for spec_file in ${{inputs.files}} ; do
          echo -e "\nChecking $spec_file…"

          $GITHUB_ACTION_PATH/perfecto-docker ${{steps.perfecto-set-options.outputs.options}} $spec_file

          if [[ $? -ne 0 ]] ; then
            check_failed=true
          fi
        done

        if [[ -n "$check_failed" ]] ; then
          exit 1
        fi
